root: true

extends: recommended

globals:
  window: true
  require: true
  define: true

rules:
  comma-dangle:
    - error
    - never
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-extra-boolean-cast:
    - 0
  no-new:
    - 0

  quotes:
    - error
    - single
  semi:
    - error
    - always